//! Generated progenitor client. Do not edit; regenerated by `build.rs` on
//! every build from `predictfun/openapi/openapi.json`.
//!
//! The generated code references `crate::openapi::state::JwtState` for its
//! inner-state type and uses an async `pre_hook` to inject the `x-api-key`
//! and (when set) `Authorization: Bearer <jwt>` headers.

#![allow(clippy::all, dead_code, unused_imports, unused_qualifications)]

include!(concat!(env!("OUT_DIR"), "/codegen.rs"));
